services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TaskZ@#1479@=
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: src/TaskZ.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TaskZ;User=sa;Password=TaskZ@#1479@=;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  sqlserver_data: